import { ExamConfig } from '@/types';

export const examConfig: ExamConfig = {
  id: 'EXAM-2024-001',
  name: 'Software Engineering Assessment',
  duration: 3600,
  maxViolations: 5,
  questions: [
    {
      id: 1,
      text: 'What is the time complexity of binary search on a sorted array of n elements?',
      options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
      correctAnswer: 1,
      category: 'Algorithms',
    },
    {
      id: 2,
      text: 'Which data structure follows the LIFO (Last In, First Out) principle?',
      options: ['Queue', 'Stack', 'Linked List', 'Heap'],
      correctAnswer: 1,
      category: 'Data Structures',
    },
    {
      id: 3,
      text: 'What does HTTP stand for?',
      options: [
        'HyperText Transfer Protocol',
        'High Transfer Text Protocol',
        'Hyperlink Text Transport Protocol',
        'HyperText Transport Program',
      ],
      correctAnswer: 0,
      category: 'Networking',
    },
    {
      id: 4,
      text: 'Which of the following is NOT a JavaScript framework or library?',
      options: ['React', 'Angular', 'Laravel', 'Vue'],
      correctAnswer: 2,
      category: 'Web Development',
    },
    {
      id: 5,
      text: 'What is a primary key in a relational database?',
      options: [
        'A key that encrypts table data',
        'A unique identifier for each record in a table',
        'The first column in every table',
        'A foreign key reference to another table',
      ],
      correctAnswer: 1,
      category: 'Databases',
    },
    {
      id: 6,
      text: 'Which sorting algorithm has the best average-case time complexity O(n log n)?',
      options: ['Bubble Sort', 'Insertion Sort', 'Quick Sort', 'Selection Sort'],
      correctAnswer: 2,
      category: 'Algorithms',
    },
    {
      id: 7,
      text: 'What does "git pull" do?',
      options: [
        'Pushes local changes to remote repository',
        'Fetches and merges remote changes into current branch',
        'Creates a new branch from remote',
        'Merges two local branches together',
      ],
      correctAnswer: 1,
      category: 'Version Control',
    },
    {
      id: 8,
      text: 'In object-oriented programming, what is encapsulation?',
      options: [
        'Creating multiple instances of a class',
        'Bundling data and methods that operate on data within a unit, hiding internal details',
        'Inheriting behavior from multiple parent classes',
        'Overriding parent class methods in child class',
      ],
      correctAnswer: 1,
      category: 'OOP Concepts',
    },
    {
      id: 9,
      text: 'Which HTTP method is typically used to update an existing resource in REST APIs?',
      options: ['GET', 'POST', 'PUT', 'DELETE'],
      correctAnswer: 2,
      category: 'Web Development',
    },
    {
      id: 10,
      text: 'What is the purpose of a "promise" in JavaScript?',
      options: [
        'To declare a variable that cannot be changed',
        'To represent the eventual completion or failure of an asynchronous operation',
        'To define a function that runs synchronously',
        'To create a copy of an object',
      ],
      correctAnswer: 1,
      category: 'JavaScript',
    },
    {
      id: 11,
      text: 'Which of the following best describes "Big O notation"?',
      options: [
        'Exact running time of an algorithm',
        'Memory usage of a program',
        'Upper bound on algorithm complexity as input size grows',
        'Number of lines of code in an algorithm',
      ],
      correctAnswer: 2,
      category: 'Algorithms',
    },
    {
      id: 12,
      text: 'What is SQL injection?',
      options: [
        'A method to speed up database queries',
        'A security vulnerability where malicious SQL is inserted into input fields',
        'A type of database backup technique',
        'A way to combine multiple SQL queries',
      ],
      correctAnswer: 1,
      category: 'Security',
    },
    {
      id: 13,
      text: 'In React, what is the virtual DOM?',
      options: [
        'A real DOM element stored in a database',
        'A server-side rendering technique',
        'A lightweight copy of the real DOM used for performance optimization',
        'A CSS styling framework',
      ],
      correctAnswer: 2,
      category: 'React',
    },
    {
      id: 14,
      text: 'What is the purpose of index in a database?',
      options: [
        'To encrypt table data for security',
        'To speed up data retrieval operations on a database table',
        'To create a backup of the database',
        'To define relationships between tables',
      ],
      correctAnswer: 1,
      category: 'Databases',
    },
    {
      id: 15,
      text: 'Which design pattern ensures a class has only one instance?',
      options: ['Factory Pattern', 'Observer Pattern', 'Singleton Pattern', 'Strategy Pattern'],
      correctAnswer: 2,
      category: 'Design Patterns',
    },
  ],
};
